name: mattermost
description: Notifies Mattermost via incoming WebHooks
author: Emmanuel Frecon <emmanuel.frecon@mitigram.com>
branding:
  icon: message-square
  color: gray-dark

inputs:
  url:
    description: |
      URL to incoming WebHook. See following URL for how to generate if your
      destination channel does not already have one hook.
      https://docs.mattermost.com/developer/webhooks-incoming.html#simple-incoming-webhook
    required: true
    default: ""
  text:
    description: |
      Markdown-formatted message to display in the post. To trigger
      notifications, use @<username>, @channel, and @here like you would in
      normal Mattermost messaging.
    required: true
    default: ""
  channel:
    description: |
      Overrides the channel the message posts in. Use the channel’s name and not
      the display name, e.g. use “town-square”, not “Town Square”. Use an “@”
      followed by a username to send to a Direct Message.
    required: false
  username:
    description: |
      Overrides the username the message posts as. Defaults to the username set
      during webhook creation or the webhook creator’s username if the former
      was not set.
    required: false
    default: "GitHub Action"
  icon_url:
    description: |
      Overrides the profile picture the message posts with. Defaults to the URL
      set during webhook creation or the webhook creator’s profile picture if
      the former was not set.
    required: false
    default: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  icon_emoji:
    description: |
      Overrides the profile picture and icon_url parameter. Defaults to none and
      is not set during webhook creation.
    required: false
  props:
    description: |
      Sets the post props, a JSON property bag for storing extra or meta data on
      the post. Mainly used by other integrations accessing posts through the
      REST API. If you want to add an extra card, use the card input instead.
    required: false
  card:
    description: |
      Props card allows for extra information (Markdown-formatted text) to be
      sent to Mattermost that will only be displayed in the RHS panel after a
      user selects the info icon displayed alongside the post.
    required: false
    default: >-
      # GitHub Information\n
      \n
      ## Action Information\n
      \n
      actor: ${{ github.actor }}\n\n
      event: ${{ github.event_name }}\n\n
      ref: ${{ github.ref }}\n\n
      repository: ${{ github.repository }}\n\n
      sha: ${{ github.sha }}\n\n
      workflow: ${{ github.workflow }}\n\n
      \n
      ## Runner Information\n
      \n
      runner: ${{ runner.name }}\n\n
      OS: ${{ runner.os }}\n\n
      \n

  options:
    description: |
      Additional options to mattermost wrapper, e.g. -v to print out additional
      verbose information. This is a semi-internal input and should only be used
      for debugging.
    required: false
    default: ""

runs:
  using: composite
  steps:
    -
      name: Notifies Mattermost
      id: mattermost
      shell: bash
      # Arrange for temporary directory to be runner's temporary directory. This
      # ensures that transient data will be removed once workflow has ended.
      env:
        TMPDIR: ${{ runner.temp }}
      run: |
        ${{ github.action_path }}/mattermost.sh \
          -t '${{ inputs.text }}' \
          -c '${{ inputs.channel }}' \
          -u '${{ inputs.username }}' \
          -i '${{ inputs.icon_url }}' \
          -e '${{ inputs.icon_emoji }}' \
          -p '${{ inputs.props }}' \
          -r '${{ inputs.card }}' \
          ${{ inputs.options }} \
          -- \
            '${{ inputs.url }}'
